#!/usr/bin/bash
export PATH=$PATH:/home/orphey/Projects/lia/.scripts/
rm .temp -rf
rm build -rf
echo "Copying files..."
mkdir .temp
mkdir build
cpp war3map.lia war3map.j -std=c99 -P -fno-extended-identifiers -w &&
cp war3map.j .temp
cp lia_deploy.w3x  .temp
cd .temp
echo "Starting map pack"
stormer ../.scripts/pack_map
echo "Optimizing map"
sleep 1
clear
WINEDEBUG=-all wine ~/Software/w3x2lni/w2l.exe slk lia_deploy.w3x
cp * ../build
cd ..
rm .temp -rf